version: '3.8'

services:
  frontend:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile  
    image: stockmaster-frontend
    container_name: stockmaster-frontend
    ports:
      - "3000:3000"
